<template>
  <q-page>
    <div class="relative-position">
      <q-img src="~assets/images/pexels1.jpg" style="height: 50vh" />
      <div class="img-resize">
        <h1 class="q-my-sm text-weight-bold title text-white">DoctoLib</h1>
        <p class="q-mt-none sub-title text-white">
          TAKE CARE OF THE PATIENT AND EVERYTHING WILL FOLLOW !
        </p>
      </div>
    </div>
    <div class="container">
      <h2 class="text-center title">About Us</h2>
      <p>
        Hospital Management System brings together all the information and
        processes of a hospital, in a single platform. It presents you with a
        unified 360-degree view for managing patients, doctors, inventory,
        appointments, billing information, finances and much more. The system
        automatically generates a highly-efficient process and makes it quick.
        Thereby, allowing hospitals to provide quality service in addition to
        professional medical care. In a nutshell, Hospital Management System
        (HMS) creates a frictionless approach towards managing the entire
        hospital and solves all complexities in the process.
      </p>
      <p>
        Patient Management The hospital management system helps register
        complete patient information. It captures and stores the medical
        history, treatment required, details of their previous visits, upcoming
        appointments if any, reports, insurance details and more. It helps
        eliminate the need to get these details on every visit. This enables the
        doctor to focus more on the treatment and improves the patient
        experience. Facility Management Every hospital or medical institution
        needs to maintain records of bed availability, occupancy status of rooms
        with specialized care and more. HMS collects all such information and
        makes it readily available whenever required. Your receptionist can
        easily check the information from the system and convey it to those who
        seek it. Staff Management The staff management module lays a concrete
        solution to the HR organization in your hospital. It contains records of
        your staff, their job description, their service domain, and other vital
        details. It helps you to know your staff without going through a heavy
        bundle of files. Additionally, it enables you to plan the hiring process
        based on the requirement in the hospital. Supply Management The supply
        management component of the HMS tracks the availability of medical
        stocks. It helps you calibrate the minimum quantity of supplies required
        without any hassle. Now, you reorder the supplies whenever stocks fall
        short. Furthermore, it also provides details of the medicine available
        so that doctors can prescribe the ones in stock. Financial Management
        This component manages all the financial affairs of your hospital. It
        calculates, stores, and presents the billing information to the
        patients. Additionally, it also records the expenses incurred by the
        hospital, revenue data, and other financial details of the hospital.
        This consolidation saves you the trouble of analyzing a colossal pile of
        record books. Insurance Management The insurance Management component of
        HMS records and stores the insurance details of the patients. On
        requirement, it furnishes the policy number, insurance company, and
        other information associated with it.
      </p>
      <p>
        The software makes it easy to fetch these details making insurance
        validation easier. Laboratory Management The laboratory management
        component shows the details of various lab-tests taken by patients. It
        furnishes reports when needed and maintains all records collectively.
        Radiology Management This component of Hospital Management System
        records and stores all reports from the radiology department of the
        hospital. It can be easily accessed by the doctors. Report Management
        Report Management module records and stores all the reports generated by
        the hospital. In the case of financial reports, It analyzes performance
        metrics to check the business profitability. Furthermore, it also
        provides a comparison between performance reports of different years.
        Support Management This segment records data of different complaints and
        requests of the patients. It also ensures that these requests and
        problems are handled properly. To summarize, the Hospital Management
        System takes care of all activities and processes involved in managing
        the hospital. But, you should understand this technology is only for
        “Managing”, the aspect of patient care is lacking in it. Patients having
        episodic treatment have to be nurtured properly. The one in the
        OutPatient Department has to be supplied with caregiving inputs so that
        they can be converted into in-patient for more advanced treatment. There
        are various other instances as well. You can provide this caregiving and
        nurturing hand with a Healthcare CRM. Healthcare CRM, when integrated
        with the Hospital Management System, will help you combine professional
        medical care with quality patient service.
      </p>
    </div>
  </q-page>
</template>

<style scoped>
.title {
  font-size: 50px;
}

.sub-title {
  font-size: 22px;
}

.img-resize {
  position: absolute;
  top: 0;
  width: 100%;
  height: 100%;
  display: flex;
  flex-flow: column;
  justify-content: center;
  align-items: center;
  background: #2c363954;
}

.contact-btn {
  color: #f1f1f1;
}
</style>
