import { ref, reactive } from "vue";
import { dateConvert } from "src/boot/dateConvert";

export default function () {
  return {
    columns: [
      {
        name: "name",
        align: "left",
        label: "Full Name",
        field: "name",
        sortable: true,
      },
      {
        name: "email",
        align: "left",
        label: "Email",
        field: "email",
        sortable: true,
      },
      {
        name: "disease",
        align: "left",
        label: "Disease",
        field: "disease",
        sortable: true,
      },
      { name: "actions", align: "right", label: "Actions" },
    ],
    filter: {
      search: "",
      company_id: "",
      name: "",
    },
    items: reactive([]),
    item: reactive({}),
    newData: reactive({
      name: "",
      email: "",
      role: "regd_patient",
      password: "",
      confirm_password: "",
      company_id: null,
      primary_contact: null,
      signed_by: "",
      identity_proof: [],
      address: "",
      gender: "",
      blood_group: "",
      age: "",
      disease: "",
      date_of_addmission: "",
      assigned_to_room: null,
      blood_pressure_level: "",
      heart_beat: "",
      sugar_level: "",
      height: "",
      weight: "",
      salary: "",
      experience: "",
    }),
    formData: reactive({
      name: "",
      email: "",
      role: "regd_patient",
      company_id: null,
      primary_contact: null,
      signed_by: "",
      identity_proof: [],
      address: "",
      gender: "",
      blood_group: "",
      age: "",
      disease: "",
      date_of_addmission: "",
      assigned_to_room: null,
      blood_pressure_level: "",
      heart_beat: "",
      sugar_level: "",
      height: "",
      weight: "",
      salary: "",
      experience: "",
    }),
    created_at: "",
    dialogs: reactive({
      createItem: false,
      editItem: false,
    }),
    lastUpdated: "",
  };
}
