import QDataTable from "components/CRUD/QDataTable.vue";
import QCreateForm from "components/CRUD/QCreateForm.vue";
import QEditForm from "components/CRUD/QEditForm.vue";
import QSearch from "components/CRUD/QSearch.vue";
import BarChart from "components/CHART/BarChart.vue";
import DoughnutChart from "components/CHART/DoughnutChart.vue";
import PieChart from "components/CHART/PieChart.vue";
import PolarAreaChart from "components/CHART/PolarAreaChart.vue";
import UploaderFile from "components/CRUD/UploaderFile.vue";
import SingleUploaderFile from "components/CRUD/SingleUploaderFile.vue";
import BedMenu from "components/BedMenu.vue";
import BedMenuR from "components/BedMenuR.vue";
import BloodAdmin from "components/BloodAdmin.vue";
import BloodDonor from "components/BloodDonor.vue";
import BloodPatient from "components/BloodPatient.vue";
import GlobalMessage from "components/GlobalMessage.vue";
import MedicineMenu from "components/MedicineMenu.vue";
import AvatarUploder from "components/AvatarUploder.vue";
import AppointmentMenu from "components/AppointmentMenu.vue";
import VisitMenu from "components/VisitMenu.vue";
import DoctorAdmin from "components/DoctorAdmin.vue";

export default ({ app }) => {
  app.component("QDataTable", QDataTable);
  app.component("QCreateForm", QCreateForm);
  app.component("QEditForm", QEditForm);
  app.component("QSearch", QSearch);
  app.component("BarChart", BarChart);
  app.component("DoughnutChart", DoughnutChart);
  app.component("PieChart", PieChart);
  app.component("PolarAreaChart", PolarAreaChart);
  app.component("UploaderFile", UploaderFile);
  app.component("SingleUploaderFile", SingleUploaderFile);
  app.component("BedMenu", BedMenu);
  app.component("BedMenuR", BedMenuR);
  app.component("BloodAdmin", BloodAdmin);
  app.component("BloodDonor", BloodDonor);
  app.component("BloodPatient", BloodPatient);
  app.component("GlobalMessage", GlobalMessage);
  app.component("MedicineMenu", MedicineMenu);
  app.component("AppointmentMenu", AppointmentMenu);
  app.component("AvatarUploder", AvatarUploder);
  app.component("VisitMenu", VisitMenu);
  app.component("DoctorAdmin", DoctorAdmin);
};
